###Lahore Air Quality & Smog Forecast

####Notebook 1: Data Cleaning
Purpose: Prepare the historical Lahore air quality dataset for machine learning by

*   loading the data,
*   checking data quality,
*   handling missing values,
*   formatting dates,

and preparing it for feature engineering.

In [124]:
import pandas as pd
import numpy as np

In [125]:
df = pd.read_csv("lahore_air_quality.csv")

In [126]:
print(df.shape)
print(df.columns)
df.head()

(335985, 16)
Index(['datetime_utc', 'location_id', 'name', 'lat', 'lon', 'hour', 'month',
       'is_smog_season', 'pm25', 'pm10', 'pm25_roll24h', 'pm10_roll24h',
       'temperature', 'relativehumidity', 'wind_speed', 'wind_direction'],
      dtype='object')

,datetime_utc,location_id,name,lat,lon,hour,month,is_smog_season,pm25,pm10,pm25_roll24h,pm10_roll24h,temperature,relativehumidity,wind_speed,wind_direction
0,2020-01-01 00:00:00+00:00,8664,US Diplomatic Post: Lahore,31.560078,74.33589,0,1,1,180.0,NaN,180.0,NaN,3.2,97,5.0,21
1,2020-01-01 01:00:00+00:00,8664,US Diplomatic Post: Lahore,31.560078,74.33589,1,1,1,255.0,NaN,217.5,NaN,3.2,98,4.3,42
2,2020-01-01 02:00:00+00:00,8664,US Diplomatic Post: Lahore,31.560078,74.33589,2,1,1,255.0,NaN,230.0,NaN,3.2,99,6.1,62
3,2020-01-01 03:00:00+00:00,8664,US Diplomatic Post: Lahore,31.560078,74.33589,3,1,1,290.0,NaN,245.0,NaN,3.6,98,6.7,74
4,2020-01-01 04:00:00+00:00,8664,US Diplomatic Post: Lahore,31.560078,74.33589,4,1,1,259.0,NaN,247.8,NaN,4.3,98,5.2,78

In [127]:
df = pd.read_csv(
    "lahore_air_quality.csv",
    engine="python"
)

In [128]:
print("Number of stations:", df["name"].nunique())

stations = sorted(df["name"].unique())
print(stations)

Number of stations: 75
['AC OFFICE NISHTAR, GAJUMATA', 'ARC, Lahore', 'Abdullah Khokhar, House Johar Town', 'Allama Iqbal Town B LHE', 'Askari 10', 'Assistant Commissioner Office, Allama Iqbal ', 'B Block, Phase 5, DHA', 'BAM,  Civil Secretariat', 'Bahria Town ', 'Barki, Lahore', 'Bedian Thethar Rd LHE', 'Burki Rd B LHE', 'CERP Office', 'Cantonment', 'Civil Secretariat', 'Climate Finance Pakistan (PakAirQuality)', 'College Road', 'Diamond Paint industries PVT LTD.', 'FF Pakistan', 'FF Pakistan - 1', 'FOOT & MOUTH DISEASE RESEARCH CENTRE', 'Ferozepur Rd A LHE', 'Forman Christian College & Chartered University', 'GENERATION Pvt ltd', 'Gajju Matta (Kahna)', 'Ghazi Road Interchange', 'Grand Charter School', 'Gulberg III', 'Gurumangat Rd B LHE', 'HBFC Society, DHA Phase 5 (Hussainy House)', 'HC - Askari 10', 'Hiking & Mountaineering Club GCU Lahore', 'Honda Gateway', 'IEEE, Punjab University, LHR', 'Johar Town', 'Johar Town B LHE', 'Kahna Hospital ', 'Kickstart MM Alam', 'LAS Lahore', 'Lahore', 'Learning Alliance Intl. DHA', 'Model Town', 'Model Town A LHE', 'Model Town B LHE', 'Model Town, CD Ground', 'NPPMCL', 'Near Ada Plot, Raiwind Road', 'Pajian, Raiwind', 'Pak Arab', 'Pakistan Engineering Services (Pvt) Ltd.', 'Phase8-DHA', 'Powerzone head office', 'Ravi Road', 'Revenue Employees Coop Housing Society', 'SOS Johar Town LHR', 'Samanabad', 'Sandha Road', 'Scarsdale International School', 'Shadman Market B LHE', 'Shalimar Town', 'Syed Maratib Ali Road', 'Test Device', 'The Bank of Punjab, Head Office, BOP Tower, Gulberg III.', 'The University of Lahore', 'Thokar Niaz Baig', 'Trinity School Lahore', 'Tufail Road near Rahat Bakery', 'US Diplomatic Post: Lahore', 'University of Central Punjab', 'University of Management and Technology', 'VTS', 'Valancia Town Lahore', 'W.R', 'WWF-PAKISTAN', 'Yani Home']

In [129]:
df["datetime_utc"] = pd.to_datetime(df["datetime_utc"])
df["date"] = df["datetime_utc"].dt.date

In [130]:
daily_df = df.groupby(["name", "date"]).agg({
    "pm25": "mean",
    "temperature": "mean",
    "relativehumidity": "mean",
    "wind_speed": "mean",
    "wind_direction": "mean",
    "lat": "first",
    "lon": "first",
    "location_id": "first",
    "is_smog_season": "first"
}).reset_index()

In [131]:
daily_df.isnull().sum()

name                0
date                0
pm25                0
temperature         0
relativehumidity    0
wind_speed          0
wind_direction      0
lat                 0
lon                 0
location_id         0
is_smog_season      0
dtype: int64

In [132]:
daily_df = daily_df.drop(columns=["pm10", "pm10_roll24h"], errors="ignore")

In [133]:
print(daily_df.shape)
print(daily_df["name"].nunique())
daily_df.head()

(15881, 11)
75

,name,date,pm25,temperature,relativehumidity,wind_speed,wind_direction,lat,lon,location_id,is_smog_season
0,"AC OFFICE NISHTAR, GAJUMATA",2025-11-20,221.500000,21.650000,57.000000,3.650000,20.500,31.377378,74.350574,6135476,1
1,"AC OFFICE NISHTAR, GAJUMATA",2025-11-21,338.000000,18.150000,70.000000,3.200000,218.500,31.377378,74.350574,6135476,1
2,"AC OFFICE NISHTAR, GAJUMATA",2025-11-23,308.000000,15.050000,73.000000,3.050000,328.000,31.377378,74.350574,6135476,1
3,"ARC, Lahore",2025-11-10,267.000000,17.669231,66.076923,1.215385,147.000,31.522056,74.314944,6125629,1
4,"ARC, Lahore",2025-11-11,267.708333,18.341667,64.875000,3.308333,208.625,31.522056,74.314944,6125629,1

In [134]:
daily_df.to_csv("lahore_air_quality_cleaned.csv", index=False)

###Reflection

In this notebook, I prepared the Lahore air quality dataset for machine learning by removing columns with extensive missing data, converting timestamps into datetime format, and sorting observations chronologically for each monitoring station. These steps ensure the dataset is ready for feature engineering and model development in the next notebook.

**NOTE:** The dataset was initially taken from kaggle, however the owner has now removed it due to unknown reasons.
https://www.kaggle.com/code/bektursyn/session/notebook